# BNA-Eval

Единая точка запуска оценки BlocksNetAgent по методике `docs/evaluation/README.md`: вопросы, прогоны агента, авто-метрики, LLM-судья, скоркарта и ручная проверка трейса.

Перед запуском проверьте `.env` с `FP2MP_CHAT_URL`/`FP2MP_API_KEY` или `CHAT_URL`/`API_KEY`.

In [1]:
MODEL = 'openai/gpt-4o'
N_RUNS = 3
M_JUDGES = 5
JUDGE_MODEL = None
QUESTIONS = 'docs/bench/questions.yaml'
CATEGORIES = None  # например ['A', 'B']
REUSE_RESULTS = None  # путь к готовому docs/bench/results_*.csv
REUSE_JUDGE = None  # путь к готовому docs/bench/judge_*.csv
RUN_JUDGE = False
MAX_ITERATIONS = 10

In [2]:
from pathlib import Path
import json
import sys
from datetime import datetime

import pandas as pd
from dotenv import load_dotenv

ROOT = Path.cwd()
for candidate in [ROOT, *ROOT.parents]:
    if (candidate / 'blocksnet_agent').exists():
        ROOT = candidate
        break
sys.path.insert(0, str(ROOT)) if str(ROOT) not in sys.path else None
load_dotenv(ROOT / '.env')

from scripts.run_bench import DEFAULT_RESULTS_DIR, _load_questions, run_benchmark
from scripts.eval_judge import case_from_result_row, judge_case, judges_to_long_rows, write_csv as write_judge_csv
from scripts.build_scorecard import build_scorecard, build_scorecard_frames

bench_dir = ROOT / 'docs' / 'bench'
stamp = datetime.now().strftime('%Y%m%d_%H%M%S')
questions_path = ROOT / QUESTIONS
bench_dir

WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench')

In [3]:
questions = _load_questions(questions_path)
if CATEGORIES:
    allowed = {item.upper() for item in CATEGORIES}
    questions = [q for q in questions if str(q.get('category', '')).upper() in allowed]
questions_df = pd.DataFrame(questions)
questions_df[['id', 'category', 'question', 'expected_tools']]

,id,category,question,expected_tools
0,q01_block_603_development,A,Что нужно разместить в квартале 603?,"[get_block_info, get_weakest_services, propose..."
1,q02_block_7_needs,A,Чего не хватает в квартале 7?,"[get_block_info, get_weakest_services]"
2,q03_block_711_provision,A,Какова обеспеченность квартала 711 сервисами?,"[get_block_info, get_weakest_services]"
3,q04_city_hotel_placement,B,Где разместить новые гостиницы?,"[compute_service_provision, suggest_target_blo..."
4,q05_city_pitch_placement,B,Где разместить спортивные площадки?,"[compute_service_provision, suggest_target_blo..."
5,q06_city_pharmacy_gaps,B,Где не хватает аптек?,"[compute_service_provision, suggest_target_blo..."
6,q07_pedestrian_streets,E/D,Какие улицы сделать пешеходными?,"[compute_connectivity, compute_mean_accessibil..."
7,q08_healthcare_gaps,C,Какие кварталы хуже всего обеспечены объектами...,"[compute_service_provision, suggest_target_blo..."
8,q09_lowest_transport_accessibility,C,Где самая низкая транспортная доступность?,[compute_mean_accessibility]
9,q10_least_connected_blocks,C,Какие кварталы наименее связны?,[compute_connectivity]
10,q11_lowest_service_diversity,C,Где самое низкое разнообразие сервисов?,[compute_shannon_diversity]
11,q12_hospital_access_population,D,Где разместить новую больницу с учётом доступн...,"[compute_service_provision, compute_mean_acces..."
12,q13_pitch_density_placement,D,Где разместить спортплощадки с учётом плотност...,"[compute_service_provision, compute_density_in..."
13,q14_service_center_centrality_gap,D,Какие кварталы лучше для нового сервисного цен...,"[compute_services_centrality, compute_service_..."
14,q15_sports_name_recovery,E,Где разместить новые спортивные объекты?,"[list_service_types, list_key_services, comput..."
15,q16_sports_centre_unavailable,E,Посчитай обеспеченность спортивными центрами.,"[list_service_types, list_key_services, comput..."
16,q17_housing_price_out_of_model,E,Какая средняя цена жилья в квартале 100?,[get_block_info]
17,q18_block_243_development,A,Что разместить в квартале 243 для роста обеспе...,"[get_block_info, get_weakest_services, propose..."

In [4]:
if REUSE_RESULTS:
    results_path = Path(REUSE_RESULTS)
    if not results_path.is_absolute():
        results_path = ROOT / results_path
else:
    results_path = bench_dir / f'results_{stamp}.csv'
    run_benchmark(
        questions_path=questions_path,
        n=N_RUNS,
        output_path=results_path,
        model=MODEL,
        max_iterations=MAX_ITERATIONS,
        categories=CATEGORIES,
    )
results_df = pd.read_csv(results_path)
results_path, results_df.head()

2026-06-17 00:44:18.151 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:18.153 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:18.166 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:18.177 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:18.369 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:18.378 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:18.379 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:18.390 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:18.401 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:18.972 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:18.978 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:18.978 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:18.987 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:18.997 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:19.104 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:19.110 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:19.111 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:19.118 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:19.129 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:20.734 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:20.741 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:20.743 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:20.751 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:20.763 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:21.435 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:21.441 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:21.442 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:21.452 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:21.463 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:21.647 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:21.652 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:21.654 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:21.661 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:21.672 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:21.967 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:21.973 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:21.974 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:21.985 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:21.998 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:22.602 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:22.608 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:22.609 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:22.616 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:22.626 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:22.795 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:22.800 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:22.800 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:22.808 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:22.818 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:23.022 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:23.027 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:23.027 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:23.035 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:23.045 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:23.358 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:23.362 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:23.363 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:23.371 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:23.381 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:24.310 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:24.315 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:24.317 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:24.325 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:24.335 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:24.795 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:24.800 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:24.802 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:24.810 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:24.820 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:25.144 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:25.149 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:25.151 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:25.159 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:25.170 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:25.874 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:25.880 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:25.881 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:25.890 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:25.901 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:26.308 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:26.313 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:26.314 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:26.322 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:26.333 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:26.617 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:26.623 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:26.624 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:26.631 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:26.642 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:26.952 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:26.957 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:26.958 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:26.967 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:26.977 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:27.752 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:27.757 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:27.758 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:27.765 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:27.774 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:28.722 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:28.730 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:28.731 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:28.739 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:28.749 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:29.730 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:29.736 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:29.737 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:29.746 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:29.755 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:30.033 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:30.038 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:30.040 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:30.049 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:30.059 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:30.537 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:30.542 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:30.543 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:30.551 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:30.562 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:30.629 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:44:30.633 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:44:30.634 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:44:30.642 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:44:30.652 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:44:30.985 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q01_block_603_development #1: D1=1.00, D2=0.75, D3=0.56, D4=0.72, category=A, selection=0.25, elapsed=48.1s

2026-06-17 00:45:04.866 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:04.867 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:04.876 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:04.886 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:05.492 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:45:05.769 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:05.771 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:05.781 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:05.794 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:06.548 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:45:06.818 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:06.819 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:06.828 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:06.839 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:07.038 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:45:07.833 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2375.92it/s]

q01_block_603_development #2: D1=1.00, D2=0.67, D3=0.52, D4=0.76, category=A, selection=0.0, elapsed=39.5s

2026-06-17 00:45:43.034 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:43.034 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:43.046 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:43.057 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:43.652 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:45:43.912 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:43.913 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:43.920 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:43.932 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:44.646 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:45:45.212 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:45:45.213 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:45:45.220 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:45:45.231 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:45:45.438 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q01_block_603_development #3: D1=1.00, D2=0.75, D3=0.52, D4=0.76, category=A, selection=0.25, elapsed=21.1s

2026-06-17 00:46:03.396 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:03.398 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:03.408 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:03.420 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:05.235 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:05.510 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:05.513 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:05.520 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:05.530 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:06.120 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:06.388 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:06.389 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:06.396 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:06.407 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:06.600 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:06.868 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:06.869 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:06.877 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:06.888 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:07.615 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q02_block_7_needs #1: D1=1.00, D2=0.83, D3=0.52, D4=0.71, category=A, selection=0.5, elapsed=23.8s

2026-06-17 00:46:27.285 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:27.287 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:27.296 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:27.307 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:27.891 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:28.144 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:28.145 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:28.155 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:28.165 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:28.373 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:29.430 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2381.05it/s]

q02_block_7_needs #2: D1=1.00, D2=0.67, D3=0.52, D4=0.76, category=A, selection=0.0, elapsed=20.8s

2026-06-17 00:46:48.457 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:48.458 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:48.469 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:48.479 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:49.068 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:49.329 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:46:49.330 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:46:49.338 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:46:49.348 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:46:50.057 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:46:50.813 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2443.40it/s]

q02_block_7_needs #3: D1=1.00, D2=0.83, D3=0.52, D4=0.76, category=A, selection=0.5, elapsed=21.4s

2026-06-17 00:47:10.341 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:47:10.343 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:47:10.351 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:47:10.362 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:47:10.951 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:47:11.444 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2423.60it/s]

q03_block_711_provision #1: D1=1.00, D2=0.67, D3=0.52, D4=0.76, category=A, selection=0.0, elapsed=29.2s

2026-06-17 00:47:39.318 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:47:39.320 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:47:39.327 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:47:39.339 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:47:39.920 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:47:40.929 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2340.94it/s]
2026-06-17 00:47:41.795 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:47:41.796 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:47:41.802 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:47:41.812 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:47:42.313 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q03_block_711_provision #2: D1=1.00, D2=0.67, D3=0.52, D4=0.76, category=A, selection=0.0, elapsed=27.5s

2026-06-17 00:48:06.794 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2434.66it/s]
2026-06-17 00:48:07.423 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:48:07.425 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:48:07.433 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:48:07.443 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:48:08.032 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q03_block_711_provision #3: D1=1.00, D2=0.83, D3=0.59, D4=0.76, category=A, selection=0.5, elapsed=25.8s

2026-06-17 00:48:33.166 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2371.52it/s]
2026-06-17 00:48:44.371 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:48:44.372 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:48:44.380 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:48:44.390 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:48:45.198 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q04_city_hotel_placement #1: D1=1.00, D2=0.75, D3=0.52, D4=0.76, category=B, selection=0.25, elapsed=36.1s

2026-06-17 00:49:09.192 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2258.28it/s]

q04_city_hotel_placement #2: D1=1.00, D2=0.67, D3=0.67, D4=0.76, category=B, selection=0.0, elapsed=24.3s

2026-06-17 00:49:33.531 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2428.26it/s]

q04_city_hotel_placement #3: D1=1.00, D2=0.67, D3=0.67, D4=0.76, category=B, selection=0.0, elapsed=31.0s

2026-06-17 00:50:03.780 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:50:03.781 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:50:03.789 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:50:03.800 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:50:04.769 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:50:06.358 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2449.25it/s]

q05_city_pitch_placement #1: D1=1.00, D2=0.75, D3=0.59, D4=0.76, category=B, selection=0.25, elapsed=42.3s

2026-06-17 00:50:47.213 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2100.55it/s]

q05_city_pitch_placement #2: D1=0.50, D2=0.67, D3=0.67, D4=0.56, category=B, selection=0.0, elapsed=25.1s

2026-06-17 00:51:11.234 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:51:11.237 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:51:11.249 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:51:11.259 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:51:12.075 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:51:12.347 | INFO     | blocksnet.relations.adjacency.core:_generate_adjacency_nodes:9 - Generating nodes
2026-06-17 00:51:12.350 | INFO     | blocksnet.relations.adjacency.core:_generate_adjacency_edges:14 - Generating edges
2026-06-17 00:51:12.660 | SUCCESS  | blocksnet.relations.adjacency.core:generate_adjacency_graph:37 - Adjacency graph successfully generated: 903 nodes, 2361 edges

q05_city_pitch_placement #3: D1=1.00, D2=0.75, D3=0.37, D4=0.29, category=B, selection=0.25, elapsed=46.6s

2026-06-17 00:51:57.353 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:51:57.355 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:51:57.362 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:51:57.373 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:51:58.386 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q06_city_pharmacy_gaps #1: D1=1.00, D2=0.83, D3=0.52, D4=0.39, category=B, selection=0.5, elapsed=27.1s

2026-06-17 00:52:23.968 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:52:23.969 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:52:23.978 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:52:23.988 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:52:24.939 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
[I 2026-06-17 00:52:53,114] A new study created in memory with name: no-name-e53cab18-22f0-4a27-9765-93b3dc9136d8
2026-06-17 00:57:56.851 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:57:56.852 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:57:56.859 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:57:56.870 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:57:57.844 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:57:58.120 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:57:58.121 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:57:58.128 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:57:58.139 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:57:59.131 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q06_city_pharmacy_gaps #2: D1=1.00, D2=0.96, D3=0.82, D4=0.96, category=B, selection=1.0, elapsed=364.3s

2026-06-17 00:58:29.369 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:58:29.371 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:58:29.380 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:58:29.392 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:58:30.353 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:58:34.692 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:58:34.693 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:58:34.704 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:58:34.714 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:58:35.670 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 00:58:35.935 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:58:35.936 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:58:35.945 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:58:35.955 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:58:36.917 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q06_city_pharmacy_gaps #3: D1=1.00, D2=0.83, D3=0.89, D4=0.71, category=B, selection=0.5, elapsed=57.3s

2026-06-17 00:59:28.084 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2219.91it/s]
2026-06-17 00:59:28.749 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 00:59:28.750 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 00:59:28.757 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 00:59:28.769 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 00:59:29.387 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q07_pedestrian_streets #1: D1=1.00, D2=0.83, D3=0.52, D4=0.51, category=E/D, selection=0.5, elapsed=46.2s

2026-06-17 01:00:23.834 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2375.79it/s]
2026-06-17 01:00:24.521 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:00:24.522 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:00:24.530 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:00:24.539 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:00:25.133 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q07_pedestrian_streets #2: D1=1.00, D2=0.83, D3=0.52, D4=0.51, category=E/D, selection=0.5, elapsed=70.2s

2026-06-17 01:01:25.921 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2377.61it/s]
2026-06-17 01:01:26.552 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:01:26.553 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:01:26.560 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:01:26.571 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:01:27.273 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:02:06.046 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:02:06.047 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:02:06.055 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:02:06.065 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:02:07.021 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:02:07.287 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:02:07.288 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:02:07.296 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:02:07.308 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:02:08.279 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q07_pedestrian_streets #3: D1=1.00, D2=0.83, D3=0.67, D4=0.71, category=E/D, selection=0.5, elapsed=70.7s

2026-06-17 01:02:37.923 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:02:37.925 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:02:37.933 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:02:37.944 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:02:38.147 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:02:39.504 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2349.77it/s]

q08_healthcare_gaps #1: D1=0.50, D2=0.83, D3=0.44, D4=0.56, category=C, selection=0.5, elapsed=55.9s

2026-06-17 01:03:30.296 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:03:30.298 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:03:30.307 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:03:30.321 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:03:30.520 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:03:30.776 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:03:30.777 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:03:30.784 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:03:30.794 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:03:31.761 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
2026-06-17 01:03:56.614 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:03:56.615 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:03:56.624 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:03:56.634 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:03:56.849 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:03:57.108 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:03:57.110 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:03:57.118 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:03:57.128 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:03:57.499 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q08_healthcare_gaps #2: D1=0.50, D2=0.97, D3=0.49, D4=0.57, category=C, selection=0.9, elapsed=82.0s

2026-06-17 01:04:52.193 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:04:52.195 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:04:52.205 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:04:52.214 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:04:52.415 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:04:53.455 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2339.88it/s]

q08_healthcare_gaps #3: D1=0.50, D2=0.83, D3=0.44, D4=0.39, category=C, selection=0.5, elapsed=61.4s

2026-06-17 01:05:53.696 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:05:53.697 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:05:53.706 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:05:53.716 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:05:55.589 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

q09_lowest_transport_accessibility #1: D1=1.00, D2=1.00, D3=0.44, D4=0.59, category=C, selection=1.0, elapsed=45.6s

2026-06-17 01:06:41.519 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:06:41.520 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:06:41.528 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:06:41.538 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:06:42.135 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
2026-06-17 01:06:42.664 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:06:42.664 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:06:42.674 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:06:42.684 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:06:42.901 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:06:43.191 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:06:43.194 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:06:43.200 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:06:43.211 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:06:43.597 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q09_lowest_transport_accessibility #2: D1=1.00, D2=1.00, D3=0.48, D4=0.56, category=C, selection=1.0, elapsed=83.8s

2026-06-17 01:08:07.728 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:08:07.730 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:08:07.737 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:08:07.749 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:08:09.602 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

q09_lowest_transport_accessibility #3: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=43.0s
q10_least_connected_blocks #1: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=50.8s
q10_least_connected_blocks #2: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=49.4s
q10_least_connected_blocks #3: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=31.4s

2026-06-17 01:11:00.819 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2299.67it/s]
2026-06-17 01:11:02.016 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:02.017 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:02.026 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:02.037 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:02.213 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:02.219 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:02.220 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:02.230 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:02.243 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:02.846 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:02.851 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:02.852 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:02.860 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:02.872 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:02.991 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:02.996 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:02.997 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:03.007 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:03.017 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:04.349 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:04.354 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:04.354 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:04.362 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:04.372 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:05.074 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:05.080 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:05.081 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:05.090 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:05.101 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:05.300 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:05.306 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:05.307 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:05.315 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:05.326 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:05.643 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:05.649 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:05.650 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:05.659 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:05.670 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:06.298 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:06.304 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:06.305 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:06.313 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:06.323 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:06.508 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:06.513 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:06.514 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:06.523 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:06.533 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:06.751 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:06.759 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:06.761 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:06.770 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:06.780 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:07.119 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:07.127 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:07.127 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:07.137 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:07.147 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:08.197 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:08.203 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:08.204 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:08.215 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:08.229 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:08.752 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:08.759 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:08.760 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:08.767 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:08.782 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:09.115 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:09.121 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:09.122 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:09.129 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:09.139 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:09.874 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:09.879 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:09.880 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:09.889 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:09.900 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:10.309 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:10.316 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:10.317 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:10.326 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:10.337 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:10.632 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:10.637 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:10.639 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:10.646 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:10.656 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:10.980 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:10.985 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:10.986 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:10.994 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:11.004 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:11.837 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:11.843 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:11.844 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:11.851 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:11.861 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:12.842 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:12.848 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:12.849 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:12.858 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:12.869 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:13.923 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:13.932 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:13.933 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:13.943 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:13.954 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:14.247 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:14.254 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:14.255 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:14.264 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:14.275 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:14.773 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:14.779 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:14.781 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:14.790 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:14.801 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:14.870 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:11:14.876 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:14.877 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:14.886 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities

q11_lowest_service_diversity #1: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=50.8s

2026-06-17 01:11:49.138 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2379.30it/s]
2026-06-17 01:11:50.735 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:11:50.736 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:11:50.745 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:11:50.755 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:11:51.444 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q11_lowest_service_diversity #2: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=35.2s

2026-06-17 01:12:25.187 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 1981.49it/s]

q11_lowest_service_diversity #3: D1=1.00, D2=1.00, D3=0.44, D4=0.39, category=C, selection=1.0, elapsed=50.6s

2026-06-17 01:13:17.302 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:13:17.304 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:13:17.312 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:13:17.324 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:13:17.531 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q12_hospital_access_population #1: D1=1.00, D2=0.93, D3=0.37, D4=0.29, category=D, selection=0.8, elapsed=41.8s

2026-06-17 01:13:56.426 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:13:56.427 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:13:56.435 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:13:56.446 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:13:56.642 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q12_hospital_access_population #2: D1=0.50, D2=0.67, D3=0.67, D4=0.32, category=D, selection=0.0, elapsed=11.8s

2026-06-17 01:14:07.938 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:14:07.940 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:14:07.951 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:14:07.961 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:14:08.167 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q12_hospital_access_population #3: D1=1.00, D2=0.80, D3=0.59, D4=0.51, category=D, selection=0.4, elapsed=53.1s

c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)
2026-06-17 01:15:01.000 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:15:01.002 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:15:01.010 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:15:01.020 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:15:01.806 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q13_pitch_density_placement #1: D1=1.00, D2=0.83, D3=0.59, D4=0.59, category=D, selection=0.5, elapsed=41.4s

2026-06-17 01:15:42.220 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:15:42.221 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:15:42.236 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:15:42.249 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:15:43.113 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q13_pitch_density_placement #2: D1=1.00, D2=0.75, D3=0.52, D4=0.39, category=D, selection=0.25, elapsed=30.7s

2026-06-17 01:16:14.060 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:16:14.062 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:16:14.070 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:16:14.081 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:16:14.885 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

q13_pitch_density_placement #3: D1=1.00, D2=0.83, D3=0.30, D4=0.29, category=D, selection=0.5, elapsed=48.7s

2026-06-17 01:17:03.858 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:17:03.859 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:17:03.867 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:17:03.878 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:17:04.859 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q14_service_center_centrality_gap #1: D1=0.50, D2=0.89, D3=0.52, D4=0.51, category=D, selection=0.6666666666666666, elapsed=80.6s

2026-06-17 01:18:22.057 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:18:22.059 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:18:22.067 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:18:22.077 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:18:23.059 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q14_service_center_centrality_gap #2: D1=0.50, D2=0.78, D3=0.52, D4=0.59, category=D, selection=0.3333333333333333, elapsed=39.7s

2026-06-17 01:19:03.667 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:03.667 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:03.675 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:03.685 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:03.870 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:03.876 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:03.877 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:03.887 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:03.898 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:04.520 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:04.524 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:04.526 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:04.533 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:04.543 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:04.655 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:04.661 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:04.662 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:04.669 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:04.684 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:05.988 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:05.994 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:05.996 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:06.004 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:06.015 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:06.702 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:06.707 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:06.708 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:06.717 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:06.727 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:06.911 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:06.916 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:06.918 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:06.926 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:06.937 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:07.229 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:07.236 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:07.237 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:07.246 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:07.256 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:07.867 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:07.871 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:07.872 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:07.879 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:07.890 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:08.059 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:08.064 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:08.065 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:08.072 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:08.084 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:08.655 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:08.660 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:08.662 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:08.670 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:08.680 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:08.995 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:09.000 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:09.001 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:09.009 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:09.020 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:09.986 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:09.991 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:09.992 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:10.000 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:10.009 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:10.506 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:10.511 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:10.512 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:10.520 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:10.531 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:10.863 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:10.869 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:10.870 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:10.878 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:10.888 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:11.602 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:11.607 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:11.608 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:11.616 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:11.625 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:12.028 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:12.034 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:12.035 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:12.043 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:12.053 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:12.339 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:12.344 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:12.345 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:12.352 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:12.362 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:12.720 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:12.725 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:12.727 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:12.734 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:12.743 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:13.573 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:13.578 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:13.579 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:13.586 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:13.597 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:14.578 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:14.583 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:14.585 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:14.593 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:14.602 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:15.619 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:15.624 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:15.624 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:15.633 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:15.643 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:15.930 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:15.934 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:15.934 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:15.942 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:15.952 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:16.457 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:16.462 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:16.464 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:16.472 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:16.482 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:16.545 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:19:16.552 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:19:16.553 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:19:16.560 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:19:16.570 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:19:16.913 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q14_service_center_centrality_gap #3: D1=0.50, D2=0.78, D3=0.56, D4=0.59, category=D, selection=0.3333333333333333, elapsed=84.8s

2026-06-17 01:20:27.401 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:20:27.402 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:20:27.410 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:20:27.421 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:20:28.296 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q15_sports_name_recovery #1: D1=1.00, D2=0.75, D3=0.44, D4=0.71, category=E, selection=0.25, elapsed=46.1s

2026-06-17 01:21:17.027 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:17.029 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:17.039 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:17.050 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:18.649 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:18.978 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:18.979 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:18.989 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:19.001 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:20.596 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:20.875 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:20.876 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:20.887 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:20.900 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:21.560 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:21.833 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:21.834 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:21.843 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:21.855 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:22.522 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:22.782 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:22.784 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:22.792 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:22.802 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:23.140 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:23.436 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:23.437 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:23.447 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:23.458 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:23.790 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:24.097 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:24.100 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:24.107 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:24.118 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:25.528 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:25.790 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:25.792 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:25.798 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:25.809 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:26.824 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:27.094 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:27.095 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:27.102 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:27.114 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:28.179 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:28.468 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:28.468 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:28.476 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:28.486 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:29.532 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:29.800 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:29.801 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:29.810 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:29.821 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:30.452 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:21:30.721 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:21:30.722 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:21:30.730 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:21:30.740 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:21:31.358 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q15_sports_name_recovery #2: D1=1.00, D2=0.67, D3=0.52, D4=0.82, category=E, selection=0.0, elapsed=83.6s
q15_sports_name_recovery #3: D1=1.00, D2=0.67, D3=0.44, D4=0.72, category=E, selection=0.0, elapsed=57.4s

2026-06-17 01:23:39.791 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:23:39.792 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:23:39.801 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:23:39.811 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:23:40.000 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:23:40.277 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:23:40.278 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:23:40.285 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:23:40.296 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:23:40.472 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:23:40.734 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:23:40.736 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:23:40.743 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:23:40.755 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:23:41.787 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\nanops.py:1016: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)
c:\Users\Eynor\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\lib\_function_base_impl.py:4653: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

q16_sports_centre_unavailable #1: D1=0.50, D2=0.82, D3=0.44, D4=0.72, category=E, selection=0.4666666666666666, elapsed=58.3s

2026-06-17 01:24:36.682 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:24:36.683 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:24:36.690 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:24:36.702 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:24:36.882 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:24:37.147 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:24:37.148 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:24:37.156 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:24:37.166 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:24:37.335 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:24:37.613 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:24:37.613 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:24:37.622 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:24:37.633 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:24:38.451 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:24:38.711 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:24:38.712 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:24:38.719 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:24:38.731 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:24:39.697 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q16_sports_centre_unavailable #2: D1=0.50, D2=0.68, D3=0.22, D4=0.29, category=E, selection=0.03333333333333327, elapsed=56.6s

2026-06-17 01:26:10.477 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:10.478 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:10.487 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:10.497 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:11.845 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:12.113 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:12.114 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:12.122 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:12.133 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:13.478 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:13.740 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:13.741 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:13.748 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:13.759 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:14.382 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:14.644 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:14.646 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:14.653 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:14.664 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:15.338 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:15.618 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:15.619 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:15.626 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:15.635 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:16.328 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:16.595 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:16.596 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:16.604 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:16.614 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:16.979 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:17.268 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:17.270 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:17.279 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:17.291 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:18.290 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:18.550 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:18.551 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:18.559 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:18.569 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:19.583 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:19.848 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:19.850 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:19.857 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:19.868 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:20.913 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:21.174 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:21.177 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:21.186 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:21.196 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:22.305 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:22.605 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:22.606 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:22.614 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:22.624 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:23.232 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:26:23.501 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:26:23.502 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:26:23.510 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:26:23.519 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:26:24.136 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q16_sports_centre_unavailable #3: D1=0.50, D2=0.67, D3=0.56, D4=0.89, category=E, selection=0.0, elapsed=89.6s

2026-06-17 01:27:01.800 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2343.67it/s]
2026-06-17 01:27:02.442 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:27:02.443 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:27:02.452 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:27:02.463 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:27:03.074 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q17_housing_price_out_of_model #1: D1=1.00, D2=0.67, D3=0.44, D4=0.52, category=E, selection=0.0, elapsed=117.7s

2026-06-17 01:29:10.442 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2356.82it/s]
2026-06-17 01:29:11.322 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:29:11.323 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:29:11.331 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:29:11.341 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:29:11.963 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q17_housing_price_out_of_model #2: D1=1.00, D2=0.67, D3=0.44, D4=0.52, category=E, selection=0.0, elapsed=71.5s

2026-06-17 01:30:12.879 | INFO     | blocksnet.analysis.diversity.shannon.core:shannon_diversity:23 - Calculating Shannon diversity index
100%|██████████| 903/903 [00:00<00:00, 2384.78it/s]
2026-06-17 01:30:13.534 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:13.535 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:13.543 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:13.555 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:14.186 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q17_housing_price_out_of_model #3: D1=1.00, D2=1.00, D3=0.44, D4=0.52, category=E, selection=1.0, elapsed=36.8s

2026-06-17 01:30:49.372 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:49.374 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:49.382 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:49.393 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:50.011 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:30:50.271 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:50.273 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:50.282 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:50.294 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:51.043 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:30:51.304 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:51.306 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:51.315 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:51.326 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:51.529 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:30:51.799 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:51.799 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:51.808 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:51.819 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:52.737 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:30:53.006 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:30:53.006 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:30:53.014 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:30:53.023 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:30:53.396 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q18_block_243_development #1: D1=0.50, D2=0.67, D3=0.44, D4=0.32, category=A, selection=0.0, elapsed=21.5s

2026-06-17 01:31:10.373 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:10.374 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:10.383 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:10.394 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:10.569 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:10.575 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:10.576 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:10.584 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:10.595 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:11.207 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:11.213 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:11.215 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:11.223 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:11.235 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:11.351 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:11.358 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:11.359 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:11.369 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:11.380 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:12.772 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:12.776 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:12.778 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:12.786 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:12.798 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:13.535 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:13.541 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:13.542 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:13.551 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:13.563 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:13.791 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:13.797 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:13.800 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:13.809 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:13.822 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:14.158 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:14.165 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:14.165 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:14.176 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:14.194 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:14.846 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:14.854 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:14.856 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:14.865 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:14.879 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:15.131 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:15.137 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:15.139 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:15.148 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:15.158 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:15.394 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:15.400 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:15.401 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:15.413 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:15.425 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:15.760 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:15.765 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:15.766 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:15.776 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:15.787 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:17.206 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:17.212 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:17.213 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:17.220 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:17.233 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:17.736 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:17.740 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:17.742 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:17.751 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:17.762 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:18.093 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:18.098 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:18.099 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:18.106 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:18.116 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:18.836 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:18.841 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:18.842 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:18.850 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:18.859 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:19.281 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:19.287 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:19.288 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:19.296 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:19.308 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:19.598 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:19.603 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:19.604 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:19.612 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:19.621 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:19.950 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:19.956 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:19.957 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:19.965 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:19.976 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:20.802 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:20.807 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:20.809 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:20.815 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:20.826 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:21.821 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:21.826 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:21.827 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:21.835 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:21.845 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:22.896 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:22.902 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:22.903 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:22.911 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:22.922 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:23.213 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:23.217 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:23.219 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:23.231 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:23.243 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:23.768 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:23.772 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:23.773 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:23.781 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:23.791 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:23.857 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:31:23.862 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:31:23.863 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:31:23.871 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:31:23.882 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:31:24.219 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q18_block_243_development #2: D1=1.00, D2=0.58, D3=0.56, D4=0.59, category=A, selection=0.25, elapsed=71.8s

2026-06-17 01:32:23.303 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:23.304 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:23.314 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:23.330 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:23.965 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:24.235 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:24.237 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:24.246 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:24.256 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:25.010 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:25.271 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:25.273 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:25.281 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:25.292 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:25.499 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:25.770 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:25.771 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:25.780 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:25.790 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:26.715 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:26.998 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:26.999 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:27.007 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:27.019 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:27.998 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:35.058 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:35.059 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:35.067 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:35.078 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:35.301 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished
2026-06-17 01:32:35.919 | INFO     | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:29 - Initializing provision DataFrame
2026-06-17 01:32:35.920 | WARNING  | blocksnet.analysis.provision.competitive.core:_initialize_provision_df:33 - No demand in columns. Imputing using population column and demand parameter
2026-06-17 01:32:35.929 | INFO     | blocksnet.analysis.provision.competitive.core:_supply_self:56 - Supplying blocks with own capacities
2026-06-17 01:32:35.939 | INFO     | blocksnet.analysis.provision.competitive.core:competitive_provision:190 - Setting and solving LP problems until max depth or break condition reached
2026-06-17 01:32:36.171 | SUCCESS  | blocksnet.analysis.provision.competitive.core:competitive_provision:203 - Provision assessment finished

q18_block_243_development #3: D1=1.00, D2=0.76, D3=0.76, D4=0.79, category=A, selection=0.35, elapsed=160.6s

(WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench/results_20260617_004403.csv'),
                           id category class  repeat  \
 0  q01_block_603_development        A     A       1
 1  q01_block_603_development        A     A       2
 2  q01_block_603_development        A     A       3
 3          q02_block_7_needs        A     A       1
 4          q02_block_7_needs        A     A       2

                                question expected_entity  expects_grounding  \
 0  Что нужно разместить в квартале 603?             603               True
 1  Что нужно разместить в квартале 603?             603               True
 2  Что нужно разместить в квартале 603?             603               True
 3         Чего не хватает в квартале 7?               7               True
 4         Чего не хватает в квартале 7?               7               True

    expects_measured  expects_out_of_model  \
 0              True                 False
 1              True                 False
 2              True                 False
 3             False                 False
 4             False                 False

                                              run_dir  ...  hyp_total  \
 0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ...          5
 1  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ...          5
 2  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ...          5
 3  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ...          5
 4  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ...          5

    hyp_supported_rate  hyp_refuted_rate  hyp_inconclusive_rate    elapsed  \
 0                 0.2               0.6                    0.2  48.102109
 1                 0.6               0.4                    0.0  39.545272
 2                 0.6               0.4                    0.0  21.109118
 3                 0.0               1.0                    0.0  23.831970
 4                 0.0               1.0                    0.0  20.809987

     D1        D2        D3     D4  composite
 0  1.0  0.750000  0.555556  0.724   0.757389
 1  1.0  0.666667  0.518519  0.756   0.735296
 2  1.0  0.750000  0.518519  0.756   0.756130
 3  1.0  0.833333  0.518519  0.710   0.765463
 4  1.0  0.666667  0.518519  0.756   0.735296

 [5 rows x 43 columns])

In [5]:
dimension_cols = ['D1', 'D2', 'D3', 'D4', 'composite']
available = [col for col in dimension_cols if col in results_df.columns]
results_df[['id', 'category', 'repeat', *available]].head()

,id,category,repeat,D1,D2,D3,D4,composite
0,q01_block_603_development,A,1,1.0,0.750000,0.555556,0.724,0.757389
1,q01_block_603_development,A,2,1.0,0.666667,0.518519,0.756,0.735296
2,q01_block_603_development,A,3,1.0,0.750000,0.518519,0.756,0.756130
3,q02_block_7_needs,A,1,1.0,0.833333,0.518519,0.710,0.765463
4,q02_block_7_needs,A,2,1.0,0.666667,0.518519,0.756,0.735296

In [6]:
judge_path = None
judge_rows = []
if REUSE_JUDGE:
    judge_path = Path(REUSE_JUDGE)
    if not judge_path.is_absolute():
        judge_path = ROOT / judge_path
elif RUN_JUDGE:
    judge_path = bench_dir / f'judge_{stamp}.csv'
    for row in results_df.to_dict('records'):
        case = case_from_result_row(row)
        evaluations = judge_case(case, n_judges=M_JUDGES, judge_model=JUDGE_MODEL)
        judge_rows.extend(judges_to_long_rows(row, evaluations))
        write_judge_csv(judge_path, judge_rows)
judge_df = pd.read_csv(judge_path) if judge_path and Path(judge_path).exists() else pd.DataFrame(judge_rows)
judge_path, judge_df.head()

(None,
 Empty DataFrame
 Columns: []
 Index: [])

In [7]:
eval_prefix = bench_dir / f'eval_{stamp}'
artifacts = build_scorecard(results_path, judge_path=judge_path, out_prefix=eval_prefix)
scorecard_df, category_df, long_df = build_scorecard_frames(results_path, judge_path=judge_path)
artifacts, scorecard_df.head(), category_df

({'wide': WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench/eval_20260617_004403.csv'),
  'long': WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench/eval_20260617_004403.long.csv'),
  'category': WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench/eval_20260617_004403.category.csv'),
  'markdown': WindowsPath('p:/AI_asistent/ITMO/blocksnet-agent/docs/bench/eval_20260617_004403.md')},
                           id category  \
 0  q01_block_603_development        A
 1          q02_block_7_needs        A
 2    q03_block_711_provision        A
 3   q04_city_hotel_placement        B
 4   q05_city_pitch_placement        B

                                         question  n  D1_median  D1_iqr  \
 0           Что нужно разместить в квартале 603?  3        1.0     0.0
 1                  Чего не хватает в квартале 7?  3        1.0     0.0
 2  Какова обеспеченность квартала 711 сервисами?  3        1.0     0.0
 3                Где разместить новые гостиницы?  3        1.0     0.0
 4            Где разместить спортивные площадки?  3        1.0     0.5

    D2_median    D2_iqr  D3_median    D3_iqr  D4_median  D4_iqr  \
 0   0.750000  0.083333   0.518519  0.037037      0.756   0.032
 1   0.833333  0.166667   0.518519  0.000000      0.756   0.046
 2   0.666667  0.166667   0.518519  0.074074      0.756   0.000
 3   0.666667  0.083333   0.666667  0.148148      0.756   0.000
 4   0.750000  0.083333   0.592593  0.296296      0.556   0.466

    composite_median  composite_iqr  calls_median  calls_iqr  \
 0          0.756130       0.022093          10.0        1.0
 1          0.765463       0.041667          11.0        1.0
 2          0.735296       0.060185          10.0        1.0
 3          0.772333       0.016204           7.0        2.0
 4          0.602593       0.177315           7.0        2.0

    wasted_calls_median                                           run_dirs
 0                  0.0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 1                  0.0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 2                  0.0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 3                  0.0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 4                  0.0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  ,
   category   n  D1_median  D1_iqr  D2_median    D2_iqr  D3_median    D3_iqr  \
 0        A  12        1.0    0.00   0.708333  0.128846   0.518519  0.037037
 1        B   9        1.0    0.00   0.750000  0.166667   0.666667  0.226852
 2        C  12        1.0    0.25   1.000000  0.016667   0.444444  0.000000
 3        D   9        1.0    0.50   0.800000  0.097222   0.518519  0.148148
 4        E   9        1.0    0.50   0.666667  0.119444   0.444444  0.037037
 5      E/D   3        1.0    0.00   0.833333  0.000000   0.518519  0.148148

    D4_median    D4_iqr  composite_median  composite_iqr  calls_median  \
 0      0.756  0.039000          0.745713       0.035917          10.0
 1      0.756  0.283000          0.772333       0.172324           7.0
 2      0.390  0.166333          0.708611       0.038611           4.0
 3      0.510  0.285000          0.605833       0.094676           5.0
 4      0.710  0.249667          0.658778       0.096250           9.0
 5      0.510  0.200000          0.715463       0.087037          10.0

    calls_iqr  wasted_calls_median  \
 0        1.5                  0.0
 1        2.0                  0.0
 2        1.0                  0.0
 3        3.0                  0.0
 4        3.5                  0.0
 5        1.0                  0.0

                                             run_dirs
 0  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 1  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 2  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 3  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 4  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
 5  p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...  )

In [8]:
display_cols = ['id', 'category', 'n', 'D1_median', 'D2_median', 'D3_median', 'D4_median', 'composite_median', 'calls_median', 'wasted_calls_median']
display(scorecard_df[[col for col in display_cols if col in scorecard_df.columns]])
display(category_df)

plot_df = category_df.set_index('category')[[col for col in ['D1_median', 'D2_median', 'D3_median', 'D4_median'] if col in category_df.columns]]
ax = plot_df.plot(kind='bar', ylim=(0, 1), figsize=(8, 4), title='BNA-Eval by category')
ax.set_ylabel('score')

,id,category,n,D1_median,D2_median,D3_median,D4_median,composite_median,calls_median,wasted_calls_median
0,q01_block_603_development,A,3,1.0,0.750000,0.518519,0.756000,0.756130,10.0,0.0
1,q02_block_7_needs,A,3,1.0,0.833333,0.518519,0.756000,0.765463,11.0,0.0
2,q03_block_711_provision,A,3,1.0,0.666667,0.518519,0.756000,0.735296,10.0,0.0
3,q04_city_hotel_placement,B,3,1.0,0.666667,0.666667,0.756000,0.772333,7.0,0.0
4,q05_city_pitch_placement,B,3,1.0,0.750000,0.592593,0.556000,0.602593,7.0,0.0
5,q06_city_pharmacy_gaps,B,3,1.0,0.833333,0.824074,0.710000,0.858056,5.0,0.0
6,q07_pedestrian_streets,E/D,3,1.0,0.833333,0.518519,0.510000,0.715463,10.0,0.0
7,q08_healthcare_gaps,C,3,0.5,0.833333,0.444444,0.556000,0.583444,5.0,0.0
8,q09_lowest_transport_accessibility,C,3,1.0,1.000000,0.444444,0.556667,0.758611,5.0,0.0
9,q10_least_connected_blocks,C,3,1.0,1.000000,0.444444,0.390000,0.708611,4.0,0.0
10,q11_lowest_service_diversity,C,3,1.0,1.000000,0.444444,0.390000,0.708611,4.0,0.0
11,q12_hospital_access_population,D,3,1.0,0.800000,0.592593,0.320000,0.648426,8.0,0.0
12,q13_pitch_density_placement,D,3,1.0,0.833333,0.518519,0.390000,0.664630,5.0,0.0
13,q14_service_center_centrality_gap,D,3,0.5,0.777778,0.518519,0.590000,0.604352,5.0,0.0
14,q15_sports_name_recovery,E,3,1.0,0.666667,0.444444,0.724000,0.726111,8.0,0.0
15,q16_sports_centre_unavailable,E,3,0.5,0.677778,0.444444,0.724000,0.622667,9.0,0.0
16,q17_housing_price_out_of_model,E,3,1.0,0.666667,0.444444,0.524000,0.658778,10.0,0.0
17,q18_block_243_development,A,3,1.0,0.666667,0.555556,0.590000,0.682222,2.0,1.0

,category,n,D1_median,D1_iqr,D2_median,D2_iqr,D3_median,D3_iqr,D4_median,D4_iqr,composite_median,composite_iqr,calls_median,calls_iqr,wasted_calls_median,run_dirs
0,A,12,1.0,0.00,0.708333,0.128846,0.518519,0.037037,0.756,0.039000,0.745713,0.035917,10.0,1.5,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
1,B,9,1.0,0.00,0.750000,0.166667,0.666667,0.226852,0.756,0.283000,0.772333,0.172324,7.0,2.0,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
2,C,12,1.0,0.25,1.000000,0.016667,0.444444,0.000000,0.390,0.166333,0.708611,0.038611,4.0,1.0,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
3,D,9,1.0,0.50,0.800000,0.097222,0.518519,0.148148,0.510,0.285000,0.605833,0.094676,5.0,3.0,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
4,E,9,1.0,0.50,0.666667,0.119444,0.444444,0.037037,0.710,0.249667,0.658778,0.096250,9.0,3.5,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...
5,E/D,3,1.0,0.00,0.833333,0.000000,0.518519,0.148148,0.510,0.200000,0.715463,0.087037,10.0,1.0,0.0,p:\AI_asistent\ITMO\blocksnet-agent\outputs\ru...

Text(0, 0.5, 'score')

In [9]:
QUESTION_ID = results_df.iloc[0]['id'] if len(results_df) else None
REPEAT = int(results_df.iloc[0]['repeat']) if len(results_df) else 1

selected = results_df[(results_df['id'] == QUESTION_ID) & (results_df['repeat'] == REPEAT)]
if len(selected):
    run_dir = Path(selected.iloc[0]['run_dir'])
    log_md = run_dir / 'run_log.md'
    print(log_md)
    print(log_md.read_text(encoding='utf-8') if log_md.exists() else 'run_log.md не найден')
    if len(judge_df):
        display(judge_df[(judge_df['id'] == QUESTION_ID) & (judge_df['repeat'].astype(str) == str(REPEAT))][['criterion', 'judge', 'score', 'evidence', 'commentary']])

p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\run_log.md
# Run Log

- Run ID: `20260617-004409-2425fc`
- Model: `openai/gpt-4o`
- Started: `2026-06-16T21:44:09+00:00`
- Finished: `2026-06-16T21:44:57+00:00`

## Question
Что нужно разместить в квартале 603?

## Confidence
- Scored (авторитетный): `0.62`
- Self-reported (модель): `0.9`

## Tool Calls
| Tool | Args | Observation |
|---|---|---|
| `compute_service_provision` | `{'service_type': 'key', 'accessibility_minutes': 15}` | Батч-обеспеченность набора 'key' (34 сервисов):<br>\| service \| threshold_min \| strong \| weak \| full_blocks \| partial_blocks \| missing_blocks \| status \|<br>\|---\|---:\|---:\|---:\|---:\|---:\|---:\|---\|<br>\| bar \| 20 \| 0.046 \| 0.046 \| 2 \| 4 \| 897 \| слабая \| |
| `compute_mean_accessibility` | `{}` | Средняя доступность (out=True) вычислена.<br>Мин: 28.34, макс: 254.04, среднее: 49.91, медиана: 33.82.<br>Топ-5 наиболее доступных (наименьшее время), mean_accessibility:<br>379    28.338085<br>253    28.379721<br>384    28.410819<br>209    28.447398<br>218     |
| `compute_services_density` | `{}` | Плотность сервисов вычислена.<br>          site_area  count_airport  count_bakery  count_bank   count_bar  count_beauty  count_bus_stop  count_cafe  count_camp  count_cinema  count_clothes  count_college  count_convenience  count_dentist  coun |
| `compute_shannon_diversity` | `{}` | shannon_diversity: мин: 0.0000, макс: 2.7801, среднее: 0.4043, медиана: 0.0000.<br>Топ-10 кварталов по разнообразию:<br>785    2.780124<br>232    2.630033<br>230    2.627341<br>845    2.579844<br>18     2.570223<br>843    2.512325<br>695    2.486503<br>235    2.42698 |
| `compute_connectivity` | `{}` | Связность вычислена.<br>Мин: 0.0039, макс: 0.0353, среднее: 0.0257.<br>Топ-5 наиболее связных кварталов:<br>379    0.035288<br>253    0.035236<br>384    0.035198<br>209    0.035153<br>218    0.035068<br>[это агрегат по городу, НЕ значение отдельного квартала; покв |
| `get_block_info` | `{'block_id': 603}` | Квартал ID=603:<br>  build_floor_area: 138016.51<br>  living_area: 109660.96<br>  non_living_area: 28355.55<br>  footprint_area: 12996.42<br>  number_of_floors: 220.0<br>  population: 3132.0<br>  is_living: 19.0<br>  count: 21.0<br>  residential: 1.0000000000000002<br>  |
| `get_metric_for_block` | `{'result_key': 'mean_accessibility', 'block_id': 603}` | 'mean_accessibility' для block_id 603: 41.0823 (медиана города 33.8192; ниже 70%, столько же 0%, выше 30% кварталов; город: мин 28.3381, макс 254.0400). |
| `get_metric_for_block` | `{'result_key': 'services_density', 'block_id': 603}` | 'services_density' для block_id 603: 0.0000 (медиана города 0.0000; ниже 64%, столько же 0%, выше 36% кварталов; город: мин 0.0000, макс 0.0024). |
| `get_metric_for_block` | `{'result_key': 'shannon_diversity', 'block_id': 603}` | 'shannon_diversity' для block_id 603: 1.3051 (медиана города 0.0000; ниже 86%, столько же 0%, выше 14% кварталов; город: мин 0.0000, макс 2.7801). |
| `get_metric_for_block` | `{'result_key': 'connectivity', 'block_id': 603}` | 'connectivity' для block_id 603: 0.0243 (медиана города 0.0296; ниже 30%, столько же 0%, выше 70% кварталов; город: мин 0.0039, макс 0.0353). |

## Saved Files
| Path | Kind | Size |
|---|---|---:|
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\competitive_provision_batch_key.csv` | csv | 2127 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\mean_accessibility.csv` | csv | 20990 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\maps\mean_accessibility.png` | map | 120514 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\services_density.csv` | csv | 139719 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\maps\services_density.png` | map | 110879 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\maps\shannon_diversity.png` | map | 121074 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\shannon_diversity.csv` | csv | 118110 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\connectivity.csv` | csv | 22948 |
| `p:\AI_asistent\ITMO\blocksnet-agent\outputs\run_20260617-004409-2425fc\maps\connectivity.png` | map | 125618 |

## Limitations
- - The analysis is based on the current model and data available in the local dataset. External factors and future developments are not considered.
- Some PTR hypotheses are inconclusive against available tool output.

## Final Answer
ANALYSIS PLAN: Для определения, что нужно разместить в квартале 603, необходимо оценить его обеспеченность ключевыми сервисами, доступность этих сервисов, плотность и разнообразие сервисов, а также связность транспортной сети. Эти метрики помогут выявить слабые места квартала и предложить конкретные улучшения. Гипотезы:
1. Block 603 имеет недостаточную обеспеченность ключевыми сервисами по сравнению с другими кварталами. Для проверки используем compute_service_provision.
2. Block 603 имеет более низкую доступность к ключевым сервисам, чем средний квартал. Для проверки используем compute_mean_accessibility.
3. Block 603 имеет более низкую плотность сервисов по сравнению с медианным кварталом. Для проверки используем compute_services_density.
4. Block 603 имеет более низкий индекс разнообразия Шеннона для сервисов, чем медианный квартал. Для проверки используем compute_shannon_diversity.
5. Block 603 имеет более низкий показатель связности по сравнению с медианным кварталом. Для проверки используем compute_connectivity.
HYPOTHESES: - id: 1; claim: Block 603 has insufficient service provision compared to other blocks.; prediction: compute_service_provision for block_id 603 < median; test: compute_service_provision; status: inconclusive; evidence: prediction could not be compared to observations
- id: 2; claim: Block 603 has lower accessibility to key services than the average block.; prediction: compute_mean_accessibility for block_id 603 < median; test: compute_mean_accessibility; status: refuted; evidence: mean_accessibility block_id 603: observed 41.0823, city median 33.8192; expected below median
- id: 3; claim: Block 603 has a lower density of services compared to the median block.; prediction: compute_services_density for block_id 603 < median; test: compute_services_density; status: refuted; evidence: services_density block_id 603: observed 0.0000, city median 0.0000; expected below median
- id: 4; claim: Block 603 has a lower Shannon diversity index of services than the median block.; prediction: compute_shannon_diversity for block_id 603 < median; test: compute_shannon_diversity; status: refuted; evidence: shannon_diversity block_id 603: observed 1.3051, city median 0.0000; expected below median
- id: 5; claim: Block 603 has a lower connectivity score compared to the median block.; prediction: compute_connectivity for block_id 603 < median; test: compute_connectivity; status: supported; evidence: connectivity block_id 603: observed 0.0243, city median 0.0296; expected below median
REFLECTION: Квартал 603 имеет значительные дефициты в обеспеченности ключевыми сервисами, особенно в таких категориях, как магазины, кафе и образовательные учреждения. Средняя доступность до сервисов также хуже, чем в среднем по городу. Плотность сервисов крайне низкая, что указывает на необходимость увеличения количества и разнообразия сервисов в этом районе. Связность транспортной сети также ниже среднего, что может затруднять доступ к сервисам.
FOLLOW_UPS: - Consider proposing specific service types to be added to block 603 to improve service provision and accessibility.
- Evaluate potential improvements in transportation connectivity to enhance access to services.
RESULT: - Обеспеченность сервисами в квартале 603 слабая для многих ключевых сервисов, таких как bakery, bar, cafe, convenience, hairdresser, hospital, hostel, houseware, kindergarten, lawyer, recruitment, restaurant, school, swimming_pool, zoo (все имеют обеспеченность 0.0000, что является минимумом по городу).
- Средняя доступность до ключевых сервисов составляет 41.08 минут, что хуже медианы по городу (33.82 минут).
- Плотность сервисов в квартале 603 равна 0.0000, что ниже медианы по городу.
- Индекс разнообразия Шеннона для квартала 603 составляет 1.3051, что выше медианы по городу (0.0000), но ниже 86% кварталов.
- Связность транспортной сети для квартала 603 составляет 0.0243, что ниже медианы по городу (0.0296).
NUMERIC SELF-CHECK: - Service provision for key services: 0.0000 for many services.
- Mean accessibility: 41.08 minutes (city median: 33.82 minutes).
- Service density: 0.0000 (city median: 0.0000).
- Shannon diversity: 1.3051 (city median: 0.0000).
- Connectivity: 0.0243 (city median: 0.0296).

In [10]:
print('results:', results_path)
print('judge:', judge_path)
for name, path in artifacts.items():
    print(name, path)

results: p:\AI_asistent\ITMO\blocksnet-agent\docs\bench\results_20260617_004403.csv
judge: None
wide p:\AI_asistent\ITMO\blocksnet-agent\docs\bench\eval_20260617_004403.csv
long p:\AI_asistent\ITMO\blocksnet-agent\docs\bench\eval_20260617_004403.long.csv
category p:\AI_asistent\ITMO\blocksnet-agent\docs\bench\eval_20260617_004403.category.csv
markdown p:\AI_asistent\ITMO\blocksnet-agent\docs\bench\eval_20260617_004403.md

## Как читать скоркарту

`D1` — понимание вопроса, `D2` — выбор инструментов, `D3` — корректность использования инструментов, `D4` — выводы и обоснование. Основной разрез — медиана и IQR по нескольким прогонам; `composite` нужен только для быстрого сравнения версий.